Add flow scrollability with checkbox
tprouvot/Chrome-Salesforce-inspector pull request #40
Opened 2023-03-19 07:43 UTC by skrissi

2023-03-20 09:03 UTC, tprouvot commented
Works like a charm 👏 

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/35368290/226293001-296d16f5-bab0-4adc-ad20-bf278a246c5e.png">

2023-03-20 09:08 UTC, tprouvot requested changes
Thanks Samuel for your contribution ! 
I have few minor comments, please reach me if you want more details.

2023-03-20 09:08 UTC, tprouvot commented on addon/button.js
> +          if (currentUrl.includes('builder_platform_interaction')) {
Great to check for the flow builder context, could you move this test at the top of the function ? So that we don't execute the code from 40 to 62 if we're not on the flow builder page ?

2023-03-20 10:27 UTC, tprouvot commented
Since the user can enable / disable flow scrollability, it would be nice to persist his choice in the localStorage.
What do you think about it ?

2023-03-20 10:29 UTC, skrissi commented
> Since the user can enable / disable flow scrollability, it would be nice to persist his choice in the localStorage. What do you think about it ?



> Since the user can enable / disable flow scrollability, it would be nice to persist his choice in the localStorage. What do you think about it ?

maybe it's good idea

2023-03-20 10:32 UTC, tprouvot requested changes

2023-03-20 10:32 UTC, tprouvot commented on addon/button.js
> +
```suggestion

```

2023-03-22 07:48 UTC, tprouvot reviewed
Thanks for the updates 👍  I have some more 😄

2023-03-22 07:48 UTC, tprouvot commented on addon/button.js
> +      checkboxState ? overflowCheckbox.checked = JSON.parse(checkboxState) : overflowCheckbox.checked = true;
```suggestion
      checkboxState ? overflowCheckbox.checked = JSON.parse(checkboxState) : overflowCheckbox.checked = true;
```

2023-03-22 07:48 UTC, tprouvot commented on addon/button.js
> +      const checkboxState = localStorage.getItem("checkboxScrollState");
How about a more precise parameter name ? Something like "scrollOnFlowBuilder" ?

2023-03-22 07:48 UTC, tprouvot commented on addon/button.js
> +      if(currentUrl.includes("sandbox")){
I understand that the UI is different from prod and sandboxes, have you tried to include the checkbox directly in the div with the class 'slds-builder-header flow-builder-header_border_icon' ? 
So that we don't have any difference from prod and sandbox plus the code is lighter 
What do you think about it ?
```suggestion
      if (currentUrl.includes("sandbox")){
```

2023-03-22 07:48 UTC, tprouvot commented on addon/button.js
> +        overflowLabel.className = "labelCheckboxScrollSandbox"
```suggestion
        overflowLabel.className = "labelCheckboxScrollSandbox";
```

2023-03-22 07:48 UTC, tprouvot commented on addon/button.js
> +      }else{
```suggestion
      } else{
```

2023-03-22 07:48 UTC, tprouvot commented on addon/button.js
> +        // Set the overflow property to "auto"
```suggestion
      // Set the overflow property to "auto"
```

2023-03-22 07:48 UTC, tprouvot commented on addon/button.js
> +      style.textContent = ".canvas {overflow : auto!important ; }";
Is it possible to handle all the style in css class instead of style element ?

2023-03-31 08:47 UTC, tprouvot approved these changes

2023-03-31 08:48 UTC, merged